### ISSUE TITLE
Account creation error Incorrect or missing CAPTCHA

### ISSUE THREAD

**Issue by Fanra** [nicjansma/mediawiki-ConfirmEdit-AreYouAHuman#3]
My website is at http://everquest.fanra.info. I used this on the create account page: http://everquest.fanra.info/index.php?title=Special:UserLogin&returnto=Main+Page&type=signup

Everything is working fine and the prove you are human says I passed the game, however when I click to create an account, I get: 

Account creation error
Incorrect or missing CAPTCHA.

It worked fine until recently and I didn't change anything.

Errors found are:

[21-May-2015 01:35:49 America/New_York] AYAH::doHttpsPostReturnJSONArray: Post to https://ws.areyouahuman.com/ws/setruntimeoptions/NUMBERREMOVEDFORSECURITY returned no result.
[21-May-2015 01:35:49 America/New_York] AYAH::getPublisherHTML: Unable to connect to the AYAH webservice server. url='https://ws.areyouahuman.com/ws/setruntimeoptions/NUMBERREMOVEDFORSECURITY';

But that was two days ago, currently there is nothing.  So that might just have been a temporary glitch in AYAH's website.

Running in DEBUG mode, I get:

DEBUG: AYAH::__construct: Publisher key: 'NUMBERREMOVEDFORSECURITY'

DEBUG: AYAH::__construct: AYAH Webservice host: 'ws.areyouahuman.com'

DEBUG: AYAH::doHttpsPost: Using cURl: url='https://ws.areyouahuman.com/ws/scoreGame';, fields='session_secret=NUMBERREMOVEDFORSECURITYscoring_key=NUMBERREMOVEDFORSECURITY'

DEBUG: AYAH::doHttpsPost: result='{"status_code":1}'

DEBUG: AYAH::__construct: Publisher key: 'NUMBERREMOVEDFORSECURITY'

DEBUG: AYAH::__construct: AYAH Webservice host: 'ws.areyouahuman.com'

DEBUG: AYAH::doHttpsPost: Using cURl: url='https://ws.areyouahuman.com/ws/setruntimeoptions/NUMBERREMOVEDFORSECURITY';, fields='config=&'

DEBUG: AYAH::doHttpsPost: result='{"status_code":1,"session_secret":null}'

**Comment by nicjansma** [comment]
Hi Fanra,

I'm not currently seeing any errors with the code on my site.  Can you confirm it's still working OK for you?

**Comment by Fanra** [comment]
Hi nicjansma,

I re-downloaded the master files here and tried again.   Now it is working.  This is strange since it is like the third time I've done it and now it works.

Still, the ways of computers are strange.  Of course, I very well might have messed up something along the way.

I'm grateful for your answer, as my quadruple checking all possible fixes as I was typing an answer to you seems to have fixed it.

Thanks again and hopefully it will continue to work.

Oh, and a huge thanks to you, and anyone else who may have contributed, for making this extension.  Spam accounts on my wiki dropped from 10 - 20 a day to none.
